### ISSUE TITLE
Get rest-client error 

### ISSUE THREAD

**Issue by ephemeral972** [snebel29/rd-tool#1]
usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rest-client (LoadError)
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/rundeck/rd-tool-master/lib/rundeck.rb:2:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/rundeck/rd-tool-master/lib/rdTool.rb:51:in `block in require_libs'
	from /var/lib/rundeck/rd-tool-master/lib/rdTool.rb:51:in `each'
	from /var/lib/rundeck/rd-tool-master/lib/rdTool.rb:51:in `require_libs'
	from /var/lib/rundeck/rd-tool-master/lib/rdTool.rb:20:in `initialize'
	from rd-tool.rb:6:in `new'
	from rd-tool.rb:6:in `<main>'

~/rd-tool-master$ ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux-gnu]

- The other question I had was how do I include the yaml file for rundeck token, I have currently done it like so

---
token: skdjfj43454545jkj...

**Comment by snebel29** [comment]
Hi @ephemeral972,
Looks like you are missing the rest-client gem so for any required gem you should install it, in the case of rd-tool

```
gem install zip
gem install rest-client
```

About your second question, I'm not sure what you mean by "include the yaml file for rundeck token" this file is automatically loaded so you should just update the config.yaml file and should this work, take a look to the code here for better understanding.

https://github.com/snebel29/rd-tool/blob/4163088d867110f9cddfb773a6026535c687ea97/lib/rundeck.rb#L10

Please let me know if you have any additional problem! I'm very happy someone is using it :-)

**Comment by ephemeral972** [comment]
I was about to write a tool to do rundeck backup and came across your tool. Good to see the tool. 
Couple of things wanted to add, it would be nice to package it into a gem so those required gems are installed using bundler and code needs to be cleaned up so it is easier to read.

I did see the config.yaml and seeing the git config thought you were referring to GIT API tokens. Anyways  will try that out, my understanding is you are doing a copy and zip of the project folder. The rundeck export tool compresses into a jar, I have not gone through your code but will do later so it would be nice to get a brief on that.
Also when I am backing up the project, does the subcommand support one project or it backs up the complete projects list.
Thanks again for this tool...hope we can improve it as we go. Cheers!!!

**Comment by ephemeral972** [comment]
I looked through your code and see that you are calling rundeck API. All good, I am closing this issue

**Comment by ephemeral972** [comment]
I added the config.yaml and I have used rundeck token for calling rundeck jobs through API but  I still get this error

/var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 403 Forbidden (RestClient::Forbidden)
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /home/rundeck/rd-tool-master/lib/rundeck.rb:23:in `get'
	from /home/rundeck/rd-tool-master/lib/rundeck.rb:104:in `project_to_file'
	from /home/rundeck/rd-tool-master/lib/rundeck.rb:65:in `block in projects_to_zip'
	from /home/rundeck/rd-tool-master/lib/rundeck.rb:61:in `each'
	from /home/rundeck/rd-tool-master/lib/rundeck.rb:61:in `projects_to_zip'
	from /home/rundeck/rd-tool-master/lib/subcommands/projects/backupToFile.rb:20:in `run'
	from /home/rundeck/rd-tool-master/lib/rdTool.rb:134:in `run'
	from rd-tool.rb:6:in `<main>'

most likely the url being build is wrong...maybe you can make the rundeck ip as parameter

**Comment by snebel29** [comment]
Hi @ephemeral972 ,
I answer you step by step:

- About the gem: Yes this would be really nice
- About how it works: The tool use the rundeck API to export/import projects to zip/jar then GIT to push/pull from repository, the tool doesn't deal with any filesystem project folder
- Support for one project in subcommands: At this point just "project restoreFromZip" subcommand support one project but would be very easy to implement the rest of commands as you can see here 
  * https://github.com/snebel29/rd-tool/blob/master/lib/subcommands/project/restoreFromZip.rb 

The tool was built thinking on being able to add more subcommands/context, this is just that I'm running out of time and I just implemented what I'm already using, but your more than welcome to participate if you want to make some pull request/suggestion! I could implement some based on requests too..

- About the 403:

The url is build here
  * https://github.com/snebel29/rd-tool/blob/master/lib/rundeck.rb#L34

Please note that by default I'm using port 80 because I'm running behind an nginx reverse proxy, but should be easy to add a port parameter to the rundeck object as well as to the config.yaml for custom configurations such as mine and let default localhost:4440 by default

As you can see here 

  * https://github.com/snebel29/rd-tool/blob/master/lib/subcommands/projects/replicateToInstance.rb#L22

Is actually possible to create the the rundeck object passing as parameter the ip or fqdn if you want as well as the port :4440 (This is the way I'm doing when connecting to remote rundeck instaces, the "ToInstance" subcommands)

Pleasre note that the acl of api_token_group should be configured properly in order for the token to work, find here an example:

api_token_group.aclpolicy

```
description: API project level access control
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create,delete] # allow create and delete jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,kill] # allow running/killing adhoc jobs and read output
  job:
    - allow: [create,read,update,delete,run,kill] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for all nodes
by:
  group: api_token_group

---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read,create,update,delete,admin] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [admin] # allow modify user profiles
  project:
    - match:
        name: '.*'
      allow: [read,import,export,configure,delete,admin] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: '.*'
      allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
  storage:
    - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content

by:
  group: api_token_group
```
